export type job = (typeof Jobs)[number]["jobs"][number];
export type department = (typeof Jobs)[number]["department"];
export type Language = (typeof Languages)[number];
export type language = Language["iso_639_1"];
export type Country = (typeof Countries)[number];
export type ProductionCountry = {
  iso_3166_1: Country["iso_3166_1"];
  name: Country["english_name"];
};
export type country = Country["iso_3166_1"];
export type TvGenre = (typeof TvGenres)[number];

export const Jobs = [
  // at tmdb, "Creator" is a feature of series, not a job
  {
    department: "Creator",
    jobs: ["Creator"],
  },
  {
    department: "Costume & Make-Up",
    jobs: [
      "Set Dressing Artist",
      "Costume Design",
      "Makeup Artist",
      "Facial Setup Artist",
      "Shoe Design",
      "Set Dressing Supervisor",
      "Set Costumer",
      "Set Dressing Manager",
      "Set Dressing Production Assistant",
      "Wigmaker",
      "Hair Setup",
      "Hairstylist",
      "Costume Supervisor",
      "Makeup Department Head",
      "On Set Dresser",
      "Truck Costumer",
      "Co-Costume Designer",
      "Tattoo Designer",
      "Additional Hairstylist",
      "Contact Lens Technician",
      "Costumer",
      "Dresser",
      "Extras Makeup Artist",
      "Makeup & Hair Assistant",
      "Hair Department Head",
      "Makeup Designer",
      "Costume Coordinator",
      "Assistant Makeup Artist",
      "Contact Lens Designer",
      "Daily Wardrobe",
      "Other",
      "Additional Wardrobe Assistant",
      "Daily Makeup & Hair",
      "First Assistant Makeup Artist",
      "Principal Costumer",
      "Special Effects Makeup Artist",
      "Wardrobe Master",
      "Key Hair Stylist",
      "Makeup Trainee",
      "Costume Consultant",
      "Lead Costumer",
      "Costume Illustrator",
      "Wig Designer",
      "Assistant Hairdresser",
      "Extras Dresser",
      "Prosthetics",
      "Prosthetics Sculptor",
      "Wardrobe Coordinator",
      "Seamstress",
      "Hair Supervisor",
      "Key Costumer",
      "Key Makeup Artist",
      "Costume Assistant",
      "Costume Standby",
      "Key Dresser",
      "Key Hairdresser",
      "Assistant Hairstylist",
      "Wardrobe Specialized Technician",
      "Hair Designer",
      "Wardrobe Supervisor",
      "Makeup & Hair",
      "Costume Mistress",
      "Hair Assistant",
      "Truck Supervisor",
      "Prosthetic Supervisor",
      "Tailor",
      "Hairdresser",
      "Wardrobe Designer",
      "Assistant Costume Designer",
      "Ager/Dyer",
      "Makeup Effects Designer",
      "Prosthetic Designer",
      "Contact Lens Painter",
      "Costume Set Supervisor",
      "Prosthetic Makeup Artist",
      "Prosthetics Painter",
      "Key Set Costumer",
      "Makeup Supervisor",
      "Costume Designer",
      "First Assistant Hairstylist",
      "Special Effects Key Makeup Artist",
      "Wardrobe Assistant",
      "Wardrobe Intern",
    ],
  },
  {
    department: "Camera",
    jobs: [
      "Steadicam Operator",
      "Additional Camera",
      "Camera Supervisor",
      "Director of Photography",
      "Camera Technician",
      "Underwater Camera",
      "Camera Operator",
      "Other",
      "Camera Department Manager",
      "Still Photographer",
      "Camera Intern",
      "Grip",
      "Aerial Director of Photography",
      "Dolly Grip",
      "Data Wrangler",
      "Epk Producer",
      'First Assistant "D" Camera',
      'Second Assistant "A" Camera',
      "Second Unit Director of Photography",
      "Best Boy Grip",
      "Camera Car",
      'First Assistant "B" Camera',
      "Underwater Epk Photographer",
      "First Assistant Camera",
      '"A" Camera Operator',
      "Additional Underwater Photography",
      "Drone Cinematographer",
      "First Company Grip",
      "Epk Camera Operator",
      '"C" Camera Operator',
      "Additional Grip",
      "Additional Key Grip",
      "Camera Truck",
      "Second Assistant Camera",
      "Aerial Camera",
      "Camera Loader",
      "Russian Arm Operator",
      "Assistant Camera",
      "Aerial Camera Technician",
      "Underwater Director of Photography",
      '"D" Camera Operator',
      "Additional Director of Photography",
      "BTS Footage",
      'First Assistant "C" Camera',
      'Second Assistant "D" Camera',
      "BTS Photographer",
      "Epk Director",
      "Libra Head Technician",
      'Third Assistant "D" Camera',
      "Camera Production Assistant",
      'Third Assistant "A" Camera',
      'Third Assistant "C" Camera',
      "Third Assistant Camera",
      "Underwater Stills Photographer",
      "Additional Still Photographer",
      "Key Grip",
      "Additional Set Photographer",
      "Clapper Loader",
      "Drone Pilot",
      'Second Assistant "C" Camera',
      'Third Assistant "B" Camera',
      'First Assistant "A" Camera',
      "Focus Puller",
      "Head of Layout",
      "Set Photographer",
      "Additional Photography",
      "Digital Imaging Technician",
      "Helicopter Camera",
      "BTS Videographer",
      "Camera Trainee",
      "Jimmy Jib Operator",
      'Second Assistant "B" Camera',
      '"B" Camera Operator',
      "Camera Department Production Assistant",
      "Phantom Operator",
      "Red Technician",
      "Videojournalist",
      "Ultimate Arm Operator",
      "Additional First Assistant Camera",
      "Additional Second Assistant Camera",
      "Assistant Grip",
      "Second Company Grip",
      "Video Report",
    ],
  },
  {
    department: "Production",
    jobs: [
      "Production Manager",
      "Finance",
      "Development Manager",
      "Administration",
      "Executive In Charge Of Post Production",
      "Location Manager",
      "Other",
      "Production Office Coordinator",
      "Production Supervisor",
      "Unit Production Manager",
      "Production Accountant",
      "Producer",
      "Executive Producer",
      "Casting",
      "Character Technical Supervisor",
      "Executive Consultant",
      "Line Producer",
      "Assistant Production Coordinator",
      "Additional Casting",
      "Controller",
      "Key Art Production Assistant",
      "Production Consultant",
      "Associate Producer",
      "Supervising Producer",
      "Delegated Producer",
      "Extras Casting Coordinator",
      "First Assistant Production Coordinator",
      "Locale Casting Director",
      "Post Producer",
      "Post Production Coordinator",
      "Co-Producer",
      "Additional Production Assistant",
      "Background Casting Director",
      "Casting Director",
      "Extras Casting Assistant",
      "Grip Production Assistant",
      "Key Set Production Assistant",
      "Casting Associate",
      "Researcher",
      "Production Coordinator",
      "Local Casting",
      "Accountant",
      "Assistant Unit Manager",
      "Attorney",
      "Contract Manager",
      "Production Executive",
      "Production Runner",
      "Production Secretary",
      "Co-Executive Producer",
      "Art Department Production Assistant",
      "Musical Casting",
      "Post Production Accountant",
      "Consulting Producer",
      "Director of Operations",
      "Executive Producer's Assistant",
      "Casting Coordinator",
      "Data Management Technician",
      "Executive Co-Producer",
      "Finishing Producer",
      "Location Casting",
      "Producer's Assistant",
      "Publicist",
      "Accounting Supervisor",
      "Head of Production",
      "Key Production Assistant",
      "Script Researcher",
      "Additional Post-Production Supervisor",
      "Feature Finishing Producer",
      "Head of Programming",
      "Key Accountant",
      "Location Assistant",
      "Unit Manager",
      "Assistant Production Manager",
      "Casting Assistant",
      "Casting Consultant",
      "Accounting Trainee",
      "Broadcast Producer",
      "Business Affairs Coordinator",
      "Insert Unit Location Manager",
      "Payroll Accountant",
      "Coordinating Producer",
      "Assistant Extras Casting",
      "Head of Research",
      "Post Coordinator",
      "Senior Executive Consultant",
      "Assistant Accountant",
      "First Assistant Accountant",
      "Original Casting",
      "Production Designer",
      "Production Director",
      "Back-up Set Production Assistant",
      "Development Producer",
      "Human Resources",
      "Key Grip Production Assistant",
      "Post Production Producer",
      "Executive In Charge Of Production",
      "Assistant Location Manager",
      "Location Coordinator",
      "Accounting Clerk Assistant",
      "Back-up Truck Production Assistant",
      "Casting Producer",
      "Casting Researcher",
      "General Manager",
      "Production Assistant",
      "Production Driver",
      "ADR Voice Casting",
      "Consulting Accountant",
      "Executive Assistant",
      "Extras Casting",
      "Location Production Assistant",
      "Post Production Technical Engineer",
      "Production Trainee",
      "Travel Coordinator",
      "Research Assistant",
      "Second Assistant Unit Manager",
      "Second Unit Location Manager",
      "Street Casting",
      "Unit Swing",
      "Truck Production Assistant",
      "Second Assistant Accountant",
      "Second Assistant Production Coordinator",
      "Trainee Production Coordinator",
    ],
  },
  {
    department: "Editing",
    jobs: [
      "Additional Editing",
      "Archival Footage Coordinator",
      "Editor",
      "Editorial Production Assistant",
      "Editorial Services",
      "First Assistant Editor",
      "Editorial Coordinator",
      "Editorial Manager",
      "Additional Editorial Assistant",
      "Archival Footage Research",
      "Supervising Film Editor",
      "Color Timer",
      "Digital Intermediate",
      "Atmos Editor",
      "Editorial Consultant",
      "First Assistant Picture Editor",
      "Lead Editor",
      "Project Manager",
      "Associate Editor",
      "Additional Editor",
      "Assistant Picture Editor",
      "Consulting Editor",
      "Dailies Technician",
      "Online Editor",
      "Stereoscopic Editor",
      "Supervising Editor",
      "3D Editor",
      "Co-Editor",
      "Dailies Manager",
      "Color Grading",
      "Dailies Operator",
      "Digital Intermediate Data Wrangler",
      "Senior Digital Intermediate Colorist",
      "Digital Colorist",
      "Colorist",
      "Other",
      "Digital Conform Editor",
      "Senior Colorist",
      "Additional Colorist",
      "Digital Intermediate Editor",
      "Negative Cutter",
      "3D Digital Colorist",
      "Assistant Editor",
      "Digital Color Timer",
      "Digital Intermediate Colorist",
      "Digital Intermediate Producer",
      "Color Assistant",
      "Digital Intermediate Assistant",
      "EPK Editor",
    ],
  },
  {
    department: "Writing",
    jobs: [
      "Storyboard",
      "Original Story",
      "Creative Producer",
      "Scenario Writer",
      "Idea",
      "Adaptation",
      "Writer",
      "Screenplay",
      "Dialogue",
      "Novel",
      "Author",
      "Other",
      "Musical",
      "Story",
      "Screenstory",
      "Characters",
      "Theatre Play",
      "Opera",
      "Series Composition",
      "Co-Writer",
      "Script Consultant",
      "Short Story",
      "Teleplay",
      "Comic Book",
      "Story Editor",
      "Book",
      "Script Editor",
      "Original Concept",
      "Original Series Creator",
      "Story Manager",
      "Executive Story Editor",
      "Junior Story Editor",
      "Story Coordinator",
      "Story Supervisor",
      "Writers' Assistant",
      "Graphic Novel",
      "Senior Story Editor",
      "Writers' Production",
      "Head of Story",
      "Lyricist",
      "Story Artist",
      "Staff Writer",
      "Story Consultant",
      "Original Film Writer",
      "Story Developer",
    ],
  },
  {
    department: "Actors",
    jobs: ["Actor", "Stunt Double", "Voice", "Special Guest", "Cameo"],
  },
  {
    department: "Lighting",
    jobs: [
      "Lighting Supervisor",
      "Best Boy Electrician",
      "Master Lighting Artist",
      "Lighting Artist",
      "Rigging Gaffer",
      "Lighting Technician",
      "Electrician",
      "Directing Lighting Artist",
      "Lighting Production Assistant",
      "Gaffer",
      "Lighting Manager",
      "Rigging Grip",
      "Best Boy Electric",
      "Lighting Coordinator",
      "Best Boy Lighting Technician",
      "Assistant Electrician",
      "Rigging Supervisor",
      "Additional Lighting Technician",
      "Lighting Programmer",
      "Other",
      "Assistant Chief Lighting Technician",
      "Daily Electrics",
      "O.B. Lighting",
      "Lighting Director",
      "Additional Gaffer",
      "Standby Rigger",
      "Underwater Gaffer",
      "Assistant Gaffer",
      "Key Rigging Grip",
      "Lighting Design",
      "Genetator Operator",
      "Chief Lighting Technician",
    ],
  },
  {
    department: "Art",
    jobs: [
      "Leadman",
      "Conceptual Design",
      "Construction Foreman",
      "Lead Painter",
      "Art Department Manager",
      "Background Designer",
      "Greensman",
      "Sign Painter",
      "Interior Designer",
      "Set Designer",
      "Standby Painter",
      "Property Master",
      "Settings",
      "Assistant Art Director",
      "Other",
      "Supervising Art Director",
      "Gun Wrangler",
      "Art Department Coordinator",
      "Co-Art Director",
      "Production Illustrator",
      "Location Scout",
      "Art Department Assistant",
      "Set Decoration Buyer",
      "Sculptor",
      "Production Design",
      "Set Decoration",
      "Construction Coordinator",
      "Art Direction",
      "Key Set Painter",
      "Swing",
      "Set Decorating Coordinator",
      "Storyboard Designer",
      "Art Designer",
      "Art Direction Intern",
      "Assistant Set Dresser",
      "Title Designer",
      "Additional Construction",
      "Property Builder",
      "Standby Art Director",
      "Assistant Production Design",
      "Head Carpenter",
      "Head Greensman",
      "Helping Hand",
      "Set Painter",
      "Special Props",
      "Additional Construction Grip",
      "Additional Storyboarding",
      "Construction Manager",
      "Props",
      "Standby Carpenter",
      "Web Designer",
      "Draughtsman",
      "Petty Cash Buyer",
      "Second Assistant Art Director",
      "Key Carpenter",
      "Original Series Design",
      "Set Dressing Buyer",
      "Supervising Carpenter",
      "Textile Artist",
      "Title Illustration",
      "Lead Set Dresser",
      "Set Dresser",
      "Creative Director",
      "Prop Designer",
      "Additional Key Construction Grip",
      "Concept Artist",
      "Main Title Designer",
      "Standby Property Master",
      "Painter",
      "Assistant Set Decoration",
      "Daily Grip",
      "First Assistant Property Master",
      "Head Designer",
      "Paint Coordinator",
      "Set Propsman",
      "Set Buyer",
      "Assistant Set Decoration Buyer",
      "First Assistant Art Direction",
      "Art Department Trainee",
      "Assistant Decorator",
      "Assistant Director of Photography",
      "Decorator",
      "Head Decorator",
      "On Set Props",
      "Storyboard Assistant",
      "Conceptual Illustrator",
      "Additional Set Dresser",
      "On Set Key Props",
      "Set Supervisor",
      "Storyboard Artist",
      "Assistant Property Master",
      "Assistant Set Propsman",
      "On Set Computer Graphics",
      "Opening Title Sequence",
      "Property Graphic Designer",
      "Construction Buyer",
      "Construction Grip",
      "Key Construction Grip",
      "Property Buyer",
      "Assistant Set Designer",
      "Digital Storyboarding",
      "Dressing Prop",
      "Graphic Designer",
      "Runner Art Department",
      "Shop Electric",
    ],
  },
  {
    department: "Directing",
    jobs: [
      "Director",
      "Script Supervisor",
      "Script Coordinator",
      "Other",
      "Layout",
      "Additional Third Assistant Director",
      "Stage Director",
      "Assistant Director Trainee",
      "First Assistant Director (Prep)",
      "Special Guest Director",
      "Assistant Director",
      "Second Second Assistant Director",
      "Action Director",
      "Crowd Assistant Director",
      "Additional Second Assistant Director",
      "Insert Unit First Assistant Director",
      "Series Director",
      "Co-Director",
      "First Assistant Director",
      "First Assistant Director Trainee",
      "Insert Unit Director",
      "Continuity",
      "Second Assistant Director Trainee",
      "Second Unit Director",
      "Second Unit First Assistant Director",
      "Second Assistant Director",
      "Third Assistant Director",
      "Field Director",
    ],
  },
  {
    department: "Visual Effects",
    jobs: [
      "Animation Manager",
      "I/O Supervisor",
      "Shading",
      "24 Frame Playback",
      "I/O Manager",
      "Animation",
      "Animation Director",
      "Animation Production Assistant",
      "VFX Supervisor",
      "Cloth Setup",
      "VFX Production Coordinator",
      "Visual Effects Producer",
      "Animation Department Coordinator",
      "Mechanical & Creature Designer",
      "Modeling",
      "Visual Effects Supervisor",
      "Battle Motion Coordinator",
      "CG Engineer",
      "CG Painter",
      "Animation Supervisor",
      "Visual Effects",
      "Chief Technician / Stop-Motion Expert",
      "Creature Design",
      "Visual Development",
      "Fix Animator",
      "Animation Fix Coordinator",
      "VFX Artist",
      "Imaging Science",
      "3D Supervisor",
      "Color Designer",
      "3D Generalist",
      "Creature Technical Director",
      "VFX Lighting Artist",
      "3D Director",
      "Digital Compositor",
      "Mechanical Designer",
      "CG Animator",
      "Lead Character Designer",
      "Visual Effects Technical Director",
      "3D Coordinator",
      "3D Sequence Supervisor",
      "VFX Director of Photography",
      "VFX Editor",
      "3D Artist",
      "Key Animation",
      "Opening/Ending Animation",
      "Visual Effects Designer",
      "Pyrotechnic Supervisor",
      "CGI Director",
      "Digital Effects Producer",
      "2D Supervisor",
      "3D Animator",
      "Character Designer",
      "Visual Effects Coordinator",
      "Additional Effects Development",
      "Simulation & Effects Production Assistant",
      "2D Artist",
      "3D Modeller",
      "Matchmove Supervisor",
      "Roto Supervisor",
      "3D Tracking Layout",
      "Lead Animator",
      "Special Effects Supervisor",
      "Stereoscopic Coordinator",
      "Simulation & Effects Artist",
      "Pre-Visualization Supervisor",
      "Character Modelling Supervisor",
      "Animation Technical Director",
      "CG Artist",
      "Compositing Supervisor",
      "Senior Animator",
      "Senior Visual Effects Supervisor",
      "Visual Effects Lineup",
      "2D Sequence Supervisor",
      "Smoke Artist",
      "Digital Film Recording",
      "Effects Supervisor",
      "Compositing Lead",
      "Director of Previsualization",
      "Head of Animation",
      "Stereoscopic Technical Director",
      "Senior Generalist",
      "Visual Effects Compositor",
      "Cyber Scanning Supervisor",
      "Senior Modeller",
      "Stereoscopic Supervisor",
      "Layout Supervisor",
      "Matte Painter",
      "Pre-Visualization Coordinator",
      "Supervising Animation Director",
      "Visual Effects Production Manager",
      "Additional Visual Effects",
      "Compositing Artist",
      "Creature Effects Technical Director",
      "Visual Effects Director",
      "Visual Effects Production Assistant",
      "Modelling Supervisor",
      "Rotoscoping Artist",
      "Pipeline Technical Director",
      "Photo Retouching",
      "Visual Effects Assistant Editor",
      "Animation Coordinator",
      "Lead Creature Designer",
      "Visual Effects Camera",
      "Generalist",
    ],
  },
  {
    department: "Crew",
    jobs: [
      "Second Unit",
      "Stunt Coordinator",
      "Schedule Coordinator",
      "Projection",
      "Picture Car Coordinator",
      "Title Graphics",
      "Department Administrator",
      "Supervisor of Production Resources",
      "Mix Technician",
      "Sequence Artist",
      "Production Intern",
      "Legal Services",
      "Choreographer",
      "Stunts",
      "Machinist",
      "Loader",
      "Supervising Technical Director",
      "Production Office Assistant",
      "Information Systems Manager",
      "Systems Administrators & Support",
      "Post-Production Manager",
      "Craft Service",
      "Propmaker",
      "Driver",
      "Second Film Editor",
      "Stand In",
      "Production Artist",
      "Post Production Assistant",
      "Motion Actor",
      "Sets & Props Supervisor",
      "Compositor",
      "Manager of Operations",
      "Temp Sound Editor",
      "Set Production Assistant",
      "Transportation Captain",
      "Temp Music Editor",
      "Software Engineer",
      "Post Production Consulting",
      "Actor's Assistant",
      "Second Unit Cinematographer",
      "Cinematography",
      "Special Effects Coordinator",
      "Production Controller",
      "Chef",
      "Steadycam",
      "Sound Design Assistant",
      "Studio Teacher",
      "Animatronic and Prosthetic Effects",
      "Supervising Animator",
      "Mixing Engineer",
      "Scenic Artist",
      "Transportation Co-Captain",
      "Translator",
      "Video Assist Operator",
      "Utility Stunts",
      "Set Production Intern",
      "Post Production Supervisor",
      "Documentation & Support",
      "Photoscience Manager",
      "Tattooist",
      "Unit Publicist",
      "Sets & Props Artist",
      "Transportation Coordinator",
      "Public Relations",
      "Telecine Colorist",
      "Sequence Lead",
      "Sequence Supervisor",
      "Motion Capture Artist",
      "Dialect Coach",
      "Security",
      "Score Engineer",
      "Special Effects",
      "Software Team Lead",
      "Special Sound Effects",
      "Cableman",
      "Set Medic",
      "Prop Maker",
      "Quality Control Supervisor",
      "Martial Arts Choreographer",
      "Armorer",
      "Digital Effects Producer",
      "Pilot",
      "Acting Double",
      "Intern",
      "Series Publicist",
      "Unit Medic",
      "Weapons Master",
      "Chaperone Tutor",
      "Dialogue Coach",
      "Military Consultant",
      "Thanks",
      "Video Game",
      "Carpenter",
      "Animatronics Designer",
      "Drone Operator",
      "Marine Coordinator",
      "Assistant Craft Service",
      "Base Camp Operator",
      "Interactive Manager",
      "Medical Consultant",
      "Sponsorship Coordinator",
      "Stunt Double",
      "Visual Effects Art Director",
      "Script",
      "Series Writer",
      "Aerial Coordinator",
      "Key Special Effects",
      "Master at Arms",
      "Special Effects Best Boy",
      "Weapons Wrangler",
      "Digital Producer",
      "Animal Coordinator",
      "Animal Wrangler",
      "Administrative Assistant",
      "Assistant Vehicles Coordinator",
      "Chaperone",
      "Child Wrangler",
      "Lighting Camera",
      "Catering Head Chef",
      "Clearances Consultant",
      "Floor Runner",
      "Special Effects Assistant",
      "Sponsorship Director",
      "Digital Effects Supervisor",
      "Makeup Effects",
      "Additional Dialogue",
      "Radio Play",
      "Cast Driver",
      "Generator Operator",
      "Key Scenic Artist",
      "Specialized Driver",
      "Vehicles Coordinator",
      "Vehicles Wrangler",
      "Associate Choreographer",
      "Graphic Novel Illustrator",
      "Pyrotechnician",
      "Assistant Script",
      "Film Processor",
      "Marine Pilot",
      "Post Production Scripts",
      "Special Effects Manager",
      "Transcriptions",
      "Other",
      "Fight Choreographer",
      "In Memory Of",
      "Captain Driver",
      "Clearances Coordinator",
      "Executive Visual Effects Producer",
      "Poem",
      "Charge Scenic Artist",
      "Health and Safety",
      "Executive in Charge of Finance",
      "Editorial Staff",
      "Presenter",
      "Catering",
      "Head Driver",
      "Logistics Coordinator",
      "CGI Supervisor",
      "Creative Consultant",
      "Executive Music Producer",
      "Assistant Picture Car Coordinator",
      "CG Supervisor",
      "Dramaturgy",
      "Creator",
      "Additional Script Supervisor",
      "Director of Communications",
      "Police Consultant",
      "Visual Effects Editor",
      "Commissioning Editor",
      "Additional Writing",
      "Animatronics Supervisor",
      "Armory Coordinator",
      "Assistant Chef",
      "Digital Supervisor",
      "Playback Coordinator",
      "Scientific Consultant",
      "Visual Effects Design Consultant",
      "Treatment",
      "File Footage",
      "Receptionist",
      "Special Effects Technician",
      "Stunt Driver",
      "Technical Advisor",
      "Technical Supervisor",
      "Additional Music",
      "Techno Crane Operator",
      "Security Coordinator",
      "Set Runner",
      "Supervising Armorer",
    ],
  },
  {
    department: "Sound",
    jobs: [
      "Sound Re-Recording Mixer",
      "Sound Engineer",
      "Foley",
      "Boom Operator",
      "Songs",
      "Music Editor",
      "Sound Effects Editor",
      "ADR & Dubbing",
      "Sound Montage Associate",
      "Music",
      "Supervising Sound Effects Editor",
      "Sound Director",
      "Additional Soundtrack",
      "Recording Supervision",
      "Sound Editor",
      "Sound Mixer",
      "Production Sound Mixer",
      "Additional Music Supervisor",
      "Original Music Composer",
      "Sound Recordist",
      "Dialogue Editor",
      "First Assistant Sound Editor",
      "Scoring Mixer",
      "Dolby Consultant",
      "Supervising Sound Editor",
      "Sound Designer",
      "Assistant Music Supervisor",
      "Conductor",
      "Sound Effects Designer",
      "Supervising Music Editor",
      "Vocal Coach",
      "ADR Supervisor",
      "Musician",
      "ADR Editor",
      "Assistant Sound Editor",
      "Sound Effects",
      "Supervising ADR Editor",
      "Apprentice Sound Editor",
      "Orchestrator",
      "Music Supervisor",
      "Music Score Producer",
      "Foley Editor",
      "Sound",
      "Additional Sound Re-Recording Mixer",
      "Utility Sound",
      "Music Director",
      "Additional Sound Re-Recordist",
      "Music Programmer",
      "Theme Song Performance",
      "Playback Singer",
      "Supervising Dialogue Editor",
      "Other",
      "ADR Recording Engineer",
      "Assistant Sound Designer",
      "ADR Coordinator",
      "Joint ADR Mixer",
      "Music Coordinator",
      "Second Assistant Sound",
      "O.B. Sound",
      "Assistant Foley Artist",
      "ADR Post Producer",
      "Foley Recordist",
      "Sound Technical Supervisor",
      "Additional Production Sound Mixer",
      "ADR Editor",
      "Keyboard Programmer",
      "Sound Post Supervisor",
      "Foley Mixer",
      "Location Sound Recordist",
      "Music Sound Design and Processing",
      "Assistant Sound Engineer",
      "Location Sound Mixer",
      "Sound Post Production Coordinator",
      "Sound Mix Technician",
      "Location Sound Assistant",
      "Loop Group Coordinator",
      "ADR Recordist",
      "Sound Supervisor",
      "ADR Engineer",
      "Audio Post Coordinator",
      "ADR Mixer",
      "Assistant Dialogue Editor",
      "Digital Foley Artist",
      "Main Title Theme Composer",
      "Music Co-Supervisor",
      "Music Consultant",
      "Foley Artist",
      "Foley Recording Engineer",
      "Music Arranger",
      "Sound Assistant",
      "Sound Re-Recording Assistant",
      "Vocals",
      "Foley Supervisor",
      "Music Producer",
      "Music Supervision Assistant",
    ],
  },
] as const;

export const ImportantRoles = 4 as const;
export const ImportantJobs: job[] = [
  "Producer",
  "Co-Producer",
  "Executive Producer",
  "Co-Executive Producer",
  "Director",
  "Co-Director",
  "Writer",
  "Co-Writer",
  "Editor",
  "Co-Editor",
  "Story Editor",
  "Script Editor",
  "Actor",
] as const;

export const Languages = [
  {
    iso_639_1: "xx",
    english_name: "No Language",
    name: "No Language",
  },
  {
    iso_639_1: "aa",
    english_name: "Afar",
    name: "",
  },
  {
    iso_639_1: "af",
    english_name: "Afrikaans",
    name: "Afrikaans",
  },
  {
    iso_639_1: "ak",
    english_name: "Akan",
    name: "",
  },
  {
    iso_639_1: "an",
    english_name: "Aragonese",
    name: "",
  },
  {
    iso_639_1: "as",
    english_name: "Assamese",
    name: "",
  },
  {
    iso_639_1: "av",
    english_name: "Avaric",
    name: "",
  },
  {
    iso_639_1: "ae",
    english_name: "Avestan",
    name: "",
  },
  {
    iso_639_1: "ay",
    english_name: "Aymara",
    name: "",
  },
  {
    iso_639_1: "az",
    english_name: "Azerbaijani",
    name: "Azərbaycan",
  },
  {
    iso_639_1: "ba",
    english_name: "Bashkir",
    name: "",
  },
  {
    iso_639_1: "bm",
    english_name: "Bambara",
    name: "Bamanankan",
  },
  {
    iso_639_1: "bn",
    english_name: "Bengali",
    name: "বাংলা",
  },
  {
    iso_639_1: "bi",
    english_name: "Bislama",
    name: "",
  },
  {
    iso_639_1: "bo",
    english_name: "Tibetan",
    name: "",
  },
  {
    iso_639_1: "bs",
    english_name: "Bosnian",
    name: "Bosanski",
  },
  {
    iso_639_1: "br",
    english_name: "Breton",
    name: "",
  },
  {
    iso_639_1: "ca",
    english_name: "Catalan",
    name: "Català",
  },
  {
    iso_639_1: "cs",
    english_name: "Czech",
    name: "Český",
  },
  {
    iso_639_1: "ch",
    english_name: "Chamorro",
    name: "Finu' Chamorro",
  },
  {
    iso_639_1: "ce",
    english_name: "Chechen",
    name: "",
  },
  {
    iso_639_1: "cu",
    english_name: "Slavic",
    name: "",
  },
  {
    iso_639_1: "cv",
    english_name: "Chuvash",
    name: "",
  },
  {
    iso_639_1: "kw",
    english_name: "Cornish",
    name: "",
  },
  {
    iso_639_1: "co",
    english_name: "Corsican",
    name: "",
  },
  {
    iso_639_1: "cr",
    english_name: "Cree",
    name: "",
  },
  {
    iso_639_1: "cy",
    english_name: "Welsh",
    name: "Cymraeg",
  },
  {
    iso_639_1: "da",
    english_name: "Danish",
    name: "Dansk",
  },
  {
    iso_639_1: "de",
    english_name: "German",
    name: "Deutsch",
  },
  {
    iso_639_1: "dv",
    english_name: "Divehi",
    name: "",
  },
  {
    iso_639_1: "dz",
    english_name: "Dzongkha",
    name: "",
  },
  {
    iso_639_1: "en",
    english_name: "English",
    name: "English",
  },
  {
    iso_639_1: "eo",
    english_name: "Esperanto",
    name: "Esperanto",
  },
  {
    iso_639_1: "et",
    english_name: "Estonian",
    name: "Eesti",
  },
  {
    iso_639_1: "eu",
    english_name: "Basque",
    name: "euskera",
  },
  {
    iso_639_1: "fo",
    english_name: "Faroese",
    name: "",
  },
  {
    iso_639_1: "fj",
    english_name: "Fijian",
    name: "",
  },
  {
    iso_639_1: "fi",
    english_name: "Finnish",
    name: "suomi",
  },
  {
    iso_639_1: "fr",
    english_name: "French",
    name: "Français",
  },
  {
    iso_639_1: "fy",
    english_name: "Frisian",
    name: "",
  },
  {
    iso_639_1: "ff",
    english_name: "Fulah",
    name: "Fulfulde",
  },
  {
    iso_639_1: "gd",
    english_name: "Gaelic",
    name: "",
  },
  {
    iso_639_1: "ga",
    english_name: "Irish",
    name: "Gaeilge",
  },
  {
    iso_639_1: "gl",
    english_name: "Galician",
    name: "Galego",
  },
  {
    iso_639_1: "gv",
    english_name: "Manx",
    name: "",
  },
  {
    iso_639_1: "gn",
    english_name: "Guarani",
    name: "",
  },
  {
    iso_639_1: "gu",
    english_name: "Gujarati",
    name: "",
  },
  {
    iso_639_1: "ht",
    english_name: "Haitian; Haitian Creole",
    name: "",
  },
  {
    iso_639_1: "ha",
    english_name: "Hausa",
    name: "Hausa",
  },
  {
    iso_639_1: "sh",
    english_name: "Serbo-Croatian",
    name: "",
  },
  {
    iso_639_1: "hz",
    english_name: "Herero",
    name: "",
  },
  {
    iso_639_1: "ho",
    english_name: "Hiri Motu",
    name: "",
  },
  {
    iso_639_1: "hr",
    english_name: "Croatian",
    name: "Hrvatski",
  },
  {
    iso_639_1: "hu",
    english_name: "Hungarian",
    name: "Magyar",
  },
  {
    iso_639_1: "ig",
    english_name: "Igbo",
    name: "",
  },
  {
    iso_639_1: "io",
    english_name: "Ido",
    name: "",
  },
  {
    iso_639_1: "ii",
    english_name: "Yi",
    name: "",
  },
  {
    iso_639_1: "iu",
    english_name: "Inuktitut",
    name: "",
  },
  {
    iso_639_1: "ie",
    english_name: "Interlingue",
    name: "",
  },
  {
    iso_639_1: "ia",
    english_name: "Interlingua",
    name: "",
  },
  {
    iso_639_1: "id",
    english_name: "Indonesian",
    name: "Bahasa indonesia",
  },
  {
    iso_639_1: "ik",
    english_name: "Inupiaq",
    name: "",
  },
  {
    iso_639_1: "is",
    english_name: "Icelandic",
    name: "Íslenska",
  },
  {
    iso_639_1: "it",
    english_name: "Italian",
    name: "Italiano",
  },
  {
    iso_639_1: "jv",
    english_name: "Javanese",
    name: "",
  },
  {
    iso_639_1: "ja",
    english_name: "Japanese",
    name: "日本語",
  },
  {
    iso_639_1: "kl",
    english_name: "Kalaallisut",
    name: "",
  },
  {
    iso_639_1: "kn",
    english_name: "Kannada",
    name: "?????",
  },
  {
    iso_639_1: "ks",
    english_name: "Kashmiri",
    name: "",
  },
  {
    iso_639_1: "ka",
    english_name: "Georgian",
    name: "ქართული",
  },
  {
    iso_639_1: "kr",
    english_name: "Kanuri",
    name: "",
  },
  {
    iso_639_1: "kk",
    english_name: "Kazakh",
    name: "қазақ",
  },
  {
    iso_639_1: "km",
    english_name: "Khmer",
    name: "",
  },
  {
    iso_639_1: "ki",
    english_name: "Kikuyu",
    name: "",
  },
  {
    iso_639_1: "rw",
    english_name: "Kinyarwanda",
    name: "Kinyarwanda",
  },
  {
    iso_639_1: "ky",
    english_name: "Kirghiz",
    name: "??????",
  },
  {
    iso_639_1: "kv",
    english_name: "Komi",
    name: "",
  },
  {
    iso_639_1: "kg",
    english_name: "Kongo",
    name: "",
  },
  {
    iso_639_1: "ko",
    english_name: "Korean",
    name: "한국어/조선말",
  },
  {
    iso_639_1: "kj",
    english_name: "Kuanyama",
    name: "",
  },
  {
    iso_639_1: "ku",
    english_name: "Kurdish",
    name: "",
  },
  {
    iso_639_1: "lo",
    english_name: "Lao",
    name: "",
  },
  {
    iso_639_1: "la",
    english_name: "Latin",
    name: "Latin",
  },
  {
    iso_639_1: "lv",
    english_name: "Latvian",
    name: "Latviešu",
  },
  {
    iso_639_1: "li",
    english_name: "Limburgish",
    name: "",
  },
  {
    iso_639_1: "ln",
    english_name: "Lingala",
    name: "",
  },
  {
    iso_639_1: "lt",
    english_name: "Lithuanian",
    name: "Lietuvių",
  },
  {
    iso_639_1: "lb",
    english_name: "Letzeburgesch",
    name: "",
  },
  {
    iso_639_1: "lu",
    english_name: "Luba-Katanga",
    name: "",
  },
  {
    iso_639_1: "lg",
    english_name: "Ganda",
    name: "",
  },
  {
    iso_639_1: "mh",
    english_name: "Marshall",
    name: "",
  },
  {
    iso_639_1: "ml",
    english_name: "Malayalam",
    name: "",
  },
  {
    iso_639_1: "mr",
    english_name: "Marathi",
    name: "",
  },
  {
    iso_639_1: "mg",
    english_name: "Malagasy",
    name: "",
  },
  {
    iso_639_1: "mt",
    english_name: "Maltese",
    name: "Malti",
  },
  {
    iso_639_1: "mo",
    english_name: "Moldavian",
    name: "",
  },
  {
    iso_639_1: "mn",
    english_name: "Mongolian",
    name: "",
  },
  {
    iso_639_1: "mi",
    english_name: "Maori",
    name: "",
  },
  {
    iso_639_1: "ms",
    english_name: "Malay",
    name: "Bahasa melayu",
  },
  {
    iso_639_1: "my",
    english_name: "Burmese",
    name: "",
  },
  {
    iso_639_1: "na",
    english_name: "Nauru",
    name: "",
  },
  {
    iso_639_1: "nv",
    english_name: "Navajo",
    name: "",
  },
  {
    iso_639_1: "nr",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "nd",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "ng",
    english_name: "Ndonga",
    name: "",
  },
  {
    iso_639_1: "ne",
    english_name: "Nepali",
    name: "",
  },
  {
    iso_639_1: "nl",
    english_name: "Dutch",
    name: "Nederlands",
  },
  {
    iso_639_1: "nn",
    english_name: "Norwegian Nynorsk",
    name: "",
  },
  {
    iso_639_1: "nb",
    english_name: "Norwegian Bokmål",
    name: "Bokmål",
  },
  {
    iso_639_1: "no",
    english_name: "Norwegian",
    name: "Norsk",
  },
  {
    iso_639_1: "ny",
    english_name: "Chichewa; Nyanja",
    name: "",
  },
  {
    iso_639_1: "oc",
    english_name: "Occitan",
    name: "",
  },
  {
    iso_639_1: "oj",
    english_name: "Ojibwa",
    name: "",
  },
  {
    iso_639_1: "or",
    english_name: "Oriya",
    name: "",
  },
  {
    iso_639_1: "om",
    english_name: "Oromo",
    name: "",
  },
  {
    iso_639_1: "os",
    english_name: "Ossetian; Ossetic",
    name: "",
  },
  {
    iso_639_1: "pa",
    english_name: "Punjabi",
    name: "ਪੰਜਾਬੀ",
  },
  {
    iso_639_1: "pi",
    english_name: "Pali",
    name: "",
  },
  {
    iso_639_1: "pl",
    english_name: "Polish",
    name: "Polski",
  },
  {
    iso_639_1: "pt",
    english_name: "Portuguese",
    name: "Português",
  },
  {
    iso_639_1: "qu",
    english_name: "Quechua",
    name: "",
  },
  {
    iso_639_1: "rm",
    english_name: "Raeto-Romance",
    name: "",
  },
  {
    iso_639_1: "ro",
    english_name: "Romanian",
    name: "Română",
  },
  {
    iso_639_1: "rn",
    english_name: "Rundi",
    name: "Kirundi",
  },
  {
    iso_639_1: "ru",
    english_name: "Russian",
    name: "Pусский",
  },
  {
    iso_639_1: "sg",
    english_name: "Sango",
    name: "",
  },
  {
    iso_639_1: "sa",
    english_name: "Sanskrit",
    name: "",
  },
  {
    iso_639_1: "si",
    english_name: "Sinhalese",
    name: "සිංහල",
  },
  {
    iso_639_1: "sk",
    english_name: "Slovak",
    name: "Slovenčina",
  },
  {
    iso_639_1: "sl",
    english_name: "Slovenian",
    name: "Slovenščina",
  },
  {
    iso_639_1: "se",
    english_name: "Northern Sami",
    name: "",
  },
  {
    iso_639_1: "sm",
    english_name: "Samoan",
    name: "",
  },
  {
    iso_639_1: "sn",
    english_name: "Shona",
    name: "",
  },
  {
    iso_639_1: "sd",
    english_name: "Sindhi",
    name: "",
  },
  {
    iso_639_1: "so",
    english_name: "Somali",
    name: "Somali",
  },
  {
    iso_639_1: "st",
    english_name: "Sotho",
    name: "",
  },
  {
    iso_639_1: "es",
    english_name: "Spanish",
    name: "Español",
  },
  {
    iso_639_1: "sq",
    english_name: "Albanian",
    name: "shqip",
  },
  {
    iso_639_1: "sc",
    english_name: "Sardinian",
    name: "",
  },
  {
    iso_639_1: "sr",
    english_name: "Serbian",
    name: "Srpski",
  },
  {
    iso_639_1: "ss",
    english_name: "Swati",
    name: "",
  },
  {
    iso_639_1: "su",
    english_name: "Sundanese",
    name: "",
  },
  {
    iso_639_1: "sw",
    english_name: "Swahili",
    name: "Kiswahili",
  },
  {
    iso_639_1: "sv",
    english_name: "Swedish",
    name: "svenska",
  },
  {
    iso_639_1: "ty",
    english_name: "Tahitian",
    name: "",
  },
  {
    iso_639_1: "ta",
    english_name: "Tamil",
    name: "தமிழ்",
  },
  {
    iso_639_1: "tt",
    english_name: "Tatar",
    name: "",
  },
  {
    iso_639_1: "te",
    english_name: "Telugu",
    name: "తెలుగు",
  },
  {
    iso_639_1: "tg",
    english_name: "Tajik",
    name: "",
  },
  {
    iso_639_1: "tl",
    english_name: "Tagalog",
    name: "",
  },
  {
    iso_639_1: "th",
    english_name: "Thai",
    name: "ภาษาไทย",
  },
  {
    iso_639_1: "ti",
    english_name: "Tigrinya",
    name: "",
  },
  {
    iso_639_1: "to",
    english_name: "Tonga",
    name: "",
  },
  {
    iso_639_1: "tn",
    english_name: "Tswana",
    name: "",
  },
  {
    iso_639_1: "ts",
    english_name: "Tsonga",
    name: "",
  },
  {
    iso_639_1: "tk",
    english_name: "Turkmen",
    name: "",
  },
  {
    iso_639_1: "tr",
    english_name: "Turkish",
    name: "Türkçe",
  },
  {
    iso_639_1: "tw",
    english_name: "Twi",
    name: "",
  },
  {
    iso_639_1: "ug",
    english_name: "Uighur",
    name: "",
  },
  {
    iso_639_1: "uk",
    english_name: "Ukrainian",
    name: "Український",
  },
  {
    iso_639_1: "ur",
    english_name: "Urdu",
    name: "اردو",
  },
  {
    iso_639_1: "uz",
    english_name: "Uzbek",
    name: "ozbek",
  },
  {
    iso_639_1: "ve",
    english_name: "Venda",
    name: "",
  },
  {
    iso_639_1: "vi",
    english_name: "Vietnamese",
    name: "Tiếng Việt",
  },
  {
    iso_639_1: "vo",
    english_name: "Volapük",
    name: "",
  },
  {
    iso_639_1: "wa",
    english_name: "Walloon",
    name: "",
  },
  {
    iso_639_1: "wo",
    english_name: "Wolof",
    name: "Wolof",
  },
  {
    iso_639_1: "xh",
    english_name: "Xhosa",
    name: "",
  },
  {
    iso_639_1: "yi",
    english_name: "Yiddish",
    name: "",
  },
  {
    iso_639_1: "za",
    english_name: "Zhuang",
    name: "",
  },
  {
    iso_639_1: "zu",
    english_name: "Zulu",
    name: "isiZulu",
  },
  {
    iso_639_1: "ab",
    english_name: "Abkhazian",
    name: "",
  },
  {
    iso_639_1: "zh",
    english_name: "Mandarin",
    name: "普通话",
  },
  {
    iso_639_1: "ps",
    english_name: "Pushto",
    name: "پښتو",
  },
  {
    iso_639_1: "am",
    english_name: "Amharic",
    name: "",
  },
  {
    iso_639_1: "ar",
    english_name: "Arabic",
    name: "العربية",
  },
  {
    iso_639_1: "be",
    english_name: "Belarusian",
    name: "беларуская мова",
  },
  {
    iso_639_1: "bg",
    english_name: "Bulgarian",
    name: "български език",
  },
  {
    iso_639_1: "cn",
    english_name: "Cantonese",
    name: "广州话 / 廣州話",
  },
  {
    iso_639_1: "mk",
    english_name: "Macedonian",
    name: "",
  },
  {
    iso_639_1: "ee",
    english_name: "Ewe",
    name: "Èʋegbe",
  },
  {
    iso_639_1: "el",
    english_name: "Greek",
    name: "ελληνικά",
  },
  {
    iso_639_1: "fa",
    english_name: "Persian",
    name: "فارسی",
  },
  {
    iso_639_1: "he",
    english_name: "Hebrew",
    name: "עִבְרִית",
  },
  {
    iso_639_1: "hi",
    english_name: "Hindi",
    name: "हिन्दी",
  },
  {
    iso_639_1: "hy",
    english_name: "Armenian",
    name: "",
  },
  {
    iso_639_1: "yo",
    english_name: "Yoruba",
    name: "Èdè Yorùbá",
  },
] as const;

export const Countries = [
  {
    iso_3166_1: "AD",
    english_name: "Andorra",
    native_name: "Andorra",
  },
  {
    iso_3166_1: "AE",
    english_name: "United Arab Emirates",
    native_name: "United Arab Emirates",
  },
  {
    iso_3166_1: "AF",
    english_name: "Afghanistan",
    native_name: "Afghanistan",
  },
  {
    iso_3166_1: "AG",
    english_name: "Antigua and Barbuda",
    native_name: "Antigua & Barbuda",
  },
  {
    iso_3166_1: "AI",
    english_name: "Anguilla",
    native_name: "Anguilla",
  },
  {
    iso_3166_1: "AL",
    english_name: "Albania",
    native_name: "Albania",
  },
  {
    iso_3166_1: "AM",
    english_name: "Armenia",
    native_name: "Armenia",
  },
  {
    iso_3166_1: "AN",
    english_name: "Netherlands Antilles",
    native_name: "Netherlands Antilles",
  },
  {
    iso_3166_1: "AO",
    english_name: "Angola",
    native_name: "Angola",
  },
  {
    iso_3166_1: "AQ",
    english_name: "Antarctica",
    native_name: "Antarctica",
  },
  {
    iso_3166_1: "AR",
    english_name: "Argentina",
    native_name: "Argentina",
  },
  {
    iso_3166_1: "AS",
    english_name: "American Samoa",
    native_name: "American Samoa",
  },
  {
    iso_3166_1: "AT",
    english_name: "Austria",
    native_name: "Austria",
  },
  {
    iso_3166_1: "AU",
    english_name: "Australia",
    native_name: "Australia",
  },
  {
    iso_3166_1: "AW",
    english_name: "Aruba",
    native_name: "Aruba",
  },
  {
    iso_3166_1: "AZ",
    english_name: "Azerbaijan",
    native_name: "Azerbaijan",
  },
  {
    iso_3166_1: "BA",
    english_name: "Bosnia and Herzegovina",
    native_name: "Bosnia & Herzegovina",
  },
  {
    iso_3166_1: "BB",
    english_name: "Barbados",
    native_name: "Barbados",
  },
  {
    iso_3166_1: "BD",
    english_name: "Bangladesh",
    native_name: "Bangladesh",
  },
  {
    iso_3166_1: "BE",
    english_name: "Belgium",
    native_name: "Belgium",
  },
  {
    iso_3166_1: "BF",
    english_name: "Burkina Faso",
    native_name: "Burkina Faso",
  },
  {
    iso_3166_1: "BG",
    english_name: "Bulgaria",
    native_name: "Bulgaria",
  },
  {
    iso_3166_1: "BH",
    english_name: "Bahrain",
    native_name: "Bahrain",
  },
  {
    iso_3166_1: "BI",
    english_name: "Burundi",
    native_name: "Burundi",
  },
  {
    iso_3166_1: "BJ",
    english_name: "Benin",
    native_name: "Benin",
  },
  {
    iso_3166_1: "BM",
    english_name: "Bermuda",
    native_name: "Bermuda",
  },
  {
    iso_3166_1: "BN",
    english_name: "Brunei Darussalam",
    native_name: "Brunei",
  },
  {
    iso_3166_1: "BO",
    english_name: "Bolivia",
    native_name: "Bolivia",
  },
  {
    iso_3166_1: "BR",
    english_name: "Brazil",
    native_name: "Brazil",
  },
  {
    iso_3166_1: "BS",
    english_name: "Bahamas",
    native_name: "Bahamas",
  },
  {
    iso_3166_1: "BT",
    english_name: "Bhutan",
    native_name: "Bhutan",
  },
  {
    iso_3166_1: "BU",
    english_name: "Burma",
    native_name: "Burma",
  },
  {
    iso_3166_1: "BV",
    english_name: "Bouvet Island",
    native_name: "Bouvet Island",
  },
  {
    iso_3166_1: "BW",
    english_name: "Botswana",
    native_name: "Botswana",
  },
  {
    iso_3166_1: "BY",
    english_name: "Belarus",
    native_name: "Belarus",
  },
  {
    iso_3166_1: "BZ",
    english_name: "Belize",
    native_name: "Belize",
  },
  {
    iso_3166_1: "CA",
    english_name: "Canada",
    native_name: "Canada",
  },
  {
    iso_3166_1: "CC",
    english_name: "Cocos  Islands",
    native_name: "Cocos (Keeling) Islands",
  },
  {
    iso_3166_1: "CD",
    english_name: "Congo",
    native_name: "Democratic Republic of the Congo (Kinshasa)",
  },
  {
    iso_3166_1: "CF",
    english_name: "Central African Republic",
    native_name: "Central African Republic",
  },
  {
    iso_3166_1: "CG",
    english_name: "Congo",
    native_name: "Republic of the Congo (Brazzaville)",
  },
  {
    iso_3166_1: "CH",
    english_name: "Switzerland",
    native_name: "Switzerland",
  },
  {
    iso_3166_1: "CI",
    english_name: "Cote D'Ivoire",
    native_name: "Côte d’Ivoire",
  },
  {
    iso_3166_1: "CK",
    english_name: "Cook Islands",
    native_name: "Cook Islands",
  },
  {
    iso_3166_1: "CL",
    english_name: "Chile",
    native_name: "Chile",
  },
  {
    iso_3166_1: "CM",
    english_name: "Cameroon",
    native_name: "Cameroon",
  },
  {
    iso_3166_1: "CN",
    english_name: "China",
    native_name: "China",
  },
  {
    iso_3166_1: "CO",
    english_name: "Colombia",
    native_name: "Colombia",
  },
  {
    iso_3166_1: "CR",
    english_name: "Costa Rica",
    native_name: "Costa Rica",
  },
  {
    iso_3166_1: "CS",
    english_name: "Serbia and Montenegro",
    native_name: "Serbia and Montenegro",
  },
  {
    iso_3166_1: "CU",
    english_name: "Cuba",
    native_name: "Cuba",
  },
  {
    iso_3166_1: "CV",
    english_name: "Cape Verde",
    native_name: "Cape Verde",
  },
  {
    iso_3166_1: "CX",
    english_name: "Christmas Island",
    native_name: "Christmas Island",
  },
  {
    iso_3166_1: "CY",
    english_name: "Cyprus",
    native_name: "Cyprus",
  },
  {
    iso_3166_1: "CZ",
    english_name: "Czech Republic",
    native_name: "Czech Republic",
  },
  {
    iso_3166_1: "DE",
    english_name: "Germany",
    native_name: "Germany",
  },
  {
    iso_3166_1: "DJ",
    english_name: "Djibouti",
    native_name: "Djibouti",
  },
  {
    iso_3166_1: "DK",
    english_name: "Denmark",
    native_name: "Denmark",
  },
  {
    iso_3166_1: "DM",
    english_name: "Dominica",
    native_name: "Dominica",
  },
  {
    iso_3166_1: "DO",
    english_name: "Dominican Republic",
    native_name: "Dominican Republic",
  },
  {
    iso_3166_1: "DZ",
    english_name: "Algeria",
    native_name: "Algeria",
  },
  {
    iso_3166_1: "EC",
    english_name: "Ecuador",
    native_name: "Ecuador",
  },
  {
    iso_3166_1: "EE",
    english_name: "Estonia",
    native_name: "Estonia",
  },
  {
    iso_3166_1: "EG",
    english_name: "Egypt",
    native_name: "Egypt",
  },
  {
    iso_3166_1: "EH",
    english_name: "Western Sahara",
    native_name: "Western Sahara",
  },
  {
    iso_3166_1: "ER",
    english_name: "Eritrea",
    native_name: "Eritrea",
  },
  {
    iso_3166_1: "ES",
    english_name: "Spain",
    native_name: "Spain",
  },
  {
    iso_3166_1: "ET",
    english_name: "Ethiopia",
    native_name: "Ethiopia",
  },
  {
    iso_3166_1: "FI",
    english_name: "Finland",
    native_name: "Finland",
  },
  {
    iso_3166_1: "FJ",
    english_name: "Fiji",
    native_name: "Fiji",
  },
  {
    iso_3166_1: "FK",
    english_name: "Falkland Islands",
    native_name: "Falkland Islands",
  },
  {
    iso_3166_1: "FM",
    english_name: "Micronesia",
    native_name: "Micronesia",
  },
  {
    iso_3166_1: "FO",
    english_name: "Faeroe Islands",
    native_name: "Faroe Islands",
  },
  {
    iso_3166_1: "FR",
    english_name: "France",
    native_name: "France",
  },
  {
    iso_3166_1: "GA",
    english_name: "Gabon",
    native_name: "Gabon",
  },
  {
    iso_3166_1: "GB",
    english_name: "United Kingdom",
    native_name: "United Kingdom",
  },
  {
    iso_3166_1: "GD",
    english_name: "Grenada",
    native_name: "Grenada",
  },
  {
    iso_3166_1: "GE",
    english_name: "Georgia",
    native_name: "Georgia",
  },
  {
    iso_3166_1: "GF",
    english_name: "French Guiana",
    native_name: "French Guiana",
  },
  {
    iso_3166_1: "GH",
    english_name: "Ghana",
    native_name: "Ghana",
  },
  {
    iso_3166_1: "GI",
    english_name: "Gibraltar",
    native_name: "Gibraltar",
  },
  {
    iso_3166_1: "GL",
    english_name: "Greenland",
    native_name: "Greenland",
  },
  {
    iso_3166_1: "GM",
    english_name: "Gambia",
    native_name: "Gambia",
  },
  {
    iso_3166_1: "GN",
    english_name: "Guinea",
    native_name: "Guinea",
  },
  {
    iso_3166_1: "GP",
    english_name: "Guadaloupe",
    native_name: "Guadeloupe",
  },
  {
    iso_3166_1: "GQ",
    english_name: "Equatorial Guinea",
    native_name: "Equatorial Guinea",
  },
  {
    iso_3166_1: "GR",
    english_name: "Greece",
    native_name: "Greece",
  },
  {
    iso_3166_1: "GS",
    english_name: "South Georgia and the South Sandwich Islands",
    native_name: "South Georgia & South Sandwich Islands",
  },
  {
    iso_3166_1: "GT",
    english_name: "Guatemala",
    native_name: "Guatemala",
  },
  {
    iso_3166_1: "GU",
    english_name: "Guam",
    native_name: "Guam",
  },
  {
    iso_3166_1: "GW",
    english_name: "Guinea-Bissau",
    native_name: "Guinea-Bissau",
  },
  {
    iso_3166_1: "GY",
    english_name: "Guyana",
    native_name: "Guyana",
  },
  {
    iso_3166_1: "HK",
    english_name: "Hong Kong",
    native_name: "Hong Kong SAR China",
  },
  {
    iso_3166_1: "HM",
    english_name: "Heard and McDonald Islands",
    native_name: "Heard & McDonald Islands",
  },
  {
    iso_3166_1: "HN",
    english_name: "Honduras",
    native_name: "Honduras",
  },
  {
    iso_3166_1: "HR",
    english_name: "Croatia",
    native_name: "Croatia",
  },
  {
    iso_3166_1: "HT",
    english_name: "Haiti",
    native_name: "Haiti",
  },
  {
    iso_3166_1: "HU",
    english_name: "Hungary",
    native_name: "Hungary",
  },
  {
    iso_3166_1: "ID",
    english_name: "Indonesia",
    native_name: "Indonesia",
  },
  {
    iso_3166_1: "IE",
    english_name: "Ireland",
    native_name: "Ireland",
  },
  {
    iso_3166_1: "IL",
    english_name: "Israel",
    native_name: "Israel",
  },
  {
    iso_3166_1: "IN",
    english_name: "India",
    native_name: "India",
  },
  {
    iso_3166_1: "IO",
    english_name: "British Indian Ocean Territory",
    native_name: "British Indian Ocean Territory",
  },
  {
    iso_3166_1: "IQ",
    english_name: "Iraq",
    native_name: "Iraq",
  },
  {
    iso_3166_1: "IR",
    english_name: "Iran",
    native_name: "Iran",
  },
  {
    iso_3166_1: "IS",
    english_name: "Iceland",
    native_name: "Iceland",
  },
  {
    iso_3166_1: "IT",
    english_name: "Italy",
    native_name: "Italy",
  },
  {
    iso_3166_1: "JM",
    english_name: "Jamaica",
    native_name: "Jamaica",
  },
  {
    iso_3166_1: "JO",
    english_name: "Jordan",
    native_name: "Jordan",
  },
  {
    iso_3166_1: "JP",
    english_name: "Japan",
    native_name: "Japan",
  },
  {
    iso_3166_1: "KE",
    english_name: "Kenya",
    native_name: "Kenya",
  },
  {
    iso_3166_1: "KG",
    english_name: "Kyrgyz Republic",
    native_name: "Kyrgyzstan",
  },
  {
    iso_3166_1: "KH",
    english_name: "Cambodia",
    native_name: "Cambodia",
  },
  {
    iso_3166_1: "KI",
    english_name: "Kiribati",
    native_name: "Kiribati",
  },
  {
    iso_3166_1: "KM",
    english_name: "Comoros",
    native_name: "Comoros",
  },
  {
    iso_3166_1: "KN",
    english_name: "St. Kitts and Nevis",
    native_name: "St. Kitts & Nevis",
  },
  {
    iso_3166_1: "KP",
    english_name: "North Korea",
    native_name: "North Korea",
  },
  {
    iso_3166_1: "KR",
    english_name: "South Korea",
    native_name: "South Korea",
  },
  {
    iso_3166_1: "KW",
    english_name: "Kuwait",
    native_name: "Kuwait",
  },
  {
    iso_3166_1: "KY",
    english_name: "Cayman Islands",
    native_name: "Cayman Islands",
  },
  {
    iso_3166_1: "KZ",
    english_name: "Kazakhstan",
    native_name: "Kazakhstan",
  },
  {
    iso_3166_1: "LA",
    english_name: "Lao People's Democratic Republic",
    native_name: "Laos",
  },
  {
    iso_3166_1: "LB",
    english_name: "Lebanon",
    native_name: "Lebanon",
  },
  {
    iso_3166_1: "LC",
    english_name: "St. Lucia",
    native_name: "St. Lucia",
  },
  {
    iso_3166_1: "LI",
    english_name: "Liechtenstein",
    native_name: "Liechtenstein",
  },
  {
    iso_3166_1: "LK",
    english_name: "Sri Lanka",
    native_name: "Sri Lanka",
  },
  {
    iso_3166_1: "LR",
    english_name: "Liberia",
    native_name: "Liberia",
  },
  {
    iso_3166_1: "LS",
    english_name: "Lesotho",
    native_name: "Lesotho",
  },
  {
    iso_3166_1: "LT",
    english_name: "Lithuania",
    native_name: "Lithuania",
  },
  {
    iso_3166_1: "LU",
    english_name: "Luxembourg",
    native_name: "Luxembourg",
  },
  {
    iso_3166_1: "LV",
    english_name: "Latvia",
    native_name: "Latvia",
  },
  {
    iso_3166_1: "LY",
    english_name: "Libyan Arab Jamahiriya",
    native_name: "Libya",
  },
  {
    iso_3166_1: "MA",
    english_name: "Morocco",
    native_name: "Morocco",
  },
  {
    iso_3166_1: "MC",
    english_name: "Monaco",
    native_name: "Monaco",
  },
  {
    iso_3166_1: "MD",
    english_name: "Moldova",
    native_name: "Moldova",
  },
  {
    iso_3166_1: "ME",
    english_name: "Montenegro",
    native_name: "Montenegro",
  },
  {
    iso_3166_1: "MG",
    english_name: "Madagascar",
    native_name: "Madagascar",
  },
  {
    iso_3166_1: "MH",
    english_name: "Marshall Islands",
    native_name: "Marshall Islands",
  },
  {
    iso_3166_1: "MK",
    english_name: "Macedonia",
    native_name: "Macedonia",
  },
  {
    iso_3166_1: "ML",
    english_name: "Mali",
    native_name: "Mali",
  },
  {
    iso_3166_1: "MM",
    english_name: "Myanmar",
    native_name: "Myanmar (Burma)",
  },
  {
    iso_3166_1: "MN",
    english_name: "Mongolia",
    native_name: "Mongolia",
  },
  {
    iso_3166_1: "MO",
    english_name: "Macao",
    native_name: "Macau SAR China",
  },
  {
    iso_3166_1: "MP",
    english_name: "Northern Mariana Islands",
    native_name: "Northern Mariana Islands",
  },
  {
    iso_3166_1: "MQ",
    english_name: "Martinique",
    native_name: "Martinique",
  },
  {
    iso_3166_1: "MR",
    english_name: "Mauritania",
    native_name: "Mauritania",
  },
  {
    iso_3166_1: "MS",
    english_name: "Montserrat",
    native_name: "Montserrat",
  },
  {
    iso_3166_1: "MT",
    english_name: "Malta",
    native_name: "Malta",
  },
  {
    iso_3166_1: "MU",
    english_name: "Mauritius",
    native_name: "Mauritius",
  },
  {
    iso_3166_1: "MV",
    english_name: "Maldives",
    native_name: "Maldives",
  },
  {
    iso_3166_1: "MW",
    english_name: "Malawi",
    native_name: "Malawi",
  },
  {
    iso_3166_1: "MX",
    english_name: "Mexico",
    native_name: "Mexico",
  },
  {
    iso_3166_1: "MY",
    english_name: "Malaysia",
    native_name: "Malaysia",
  },
  {
    iso_3166_1: "MZ",
    english_name: "Mozambique",
    native_name: "Mozambique",
  },
  {
    iso_3166_1: "NA",
    english_name: "Namibia",
    native_name: "Namibia",
  },
  {
    iso_3166_1: "NC",
    english_name: "New Caledonia",
    native_name: "New Caledonia",
  },
  {
    iso_3166_1: "NE",
    english_name: "Niger",
    native_name: "Niger",
  },
  {
    iso_3166_1: "NF",
    english_name: "Norfolk Island",
    native_name: "Norfolk Island",
  },
  {
    iso_3166_1: "NG",
    english_name: "Nigeria",
    native_name: "Nigeria",
  },
  {
    iso_3166_1: "NI",
    english_name: "Nicaragua",
    native_name: "Nicaragua",
  },
  {
    iso_3166_1: "NL",
    english_name: "Netherlands",
    native_name: "Netherlands",
  },
  {
    iso_3166_1: "NO",
    english_name: "Norway",
    native_name: "Norway",
  },
  {
    iso_3166_1: "NP",
    english_name: "Nepal",
    native_name: "Nepal",
  },
  {
    iso_3166_1: "NR",
    english_name: "Nauru",
    native_name: "Nauru",
  },
  {
    iso_3166_1: "NU",
    english_name: "Niue",
    native_name: "Niue",
  },
  {
    iso_3166_1: "NZ",
    english_name: "New Zealand",
    native_name: "New Zealand",
  },
  {
    iso_3166_1: "OM",
    english_name: "Oman",
    native_name: "Oman",
  },
  {
    iso_3166_1: "PA",
    english_name: "Panama",
    native_name: "Panama",
  },
  {
    iso_3166_1: "PE",
    english_name: "Peru",
    native_name: "Peru",
  },
  {
    iso_3166_1: "PF",
    english_name: "French Polynesia",
    native_name: "French Polynesia",
  },
  {
    iso_3166_1: "PG",
    english_name: "Papua New Guinea",
    native_name: "Papua New Guinea",
  },
  {
    iso_3166_1: "PH",
    english_name: "Philippines",
    native_name: "Philippines",
  },
  {
    iso_3166_1: "PK",
    english_name: "Pakistan",
    native_name: "Pakistan",
  },
  {
    iso_3166_1: "PL",
    english_name: "Poland",
    native_name: "Poland",
  },
  {
    iso_3166_1: "PM",
    english_name: "St. Pierre and Miquelon",
    native_name: "St. Pierre & Miquelon",
  },
  {
    iso_3166_1: "PN",
    english_name: "Pitcairn Island",
    native_name: "Pitcairn Islands",
  },
  {
    iso_3166_1: "PR",
    english_name: "Puerto Rico",
    native_name: "Puerto Rico",
  },
  {
    iso_3166_1: "PS",
    english_name: "Palestinian Territory",
    native_name: "Palestinian Territories",
  },
  {
    iso_3166_1: "PT",
    english_name: "Portugal",
    native_name: "Portugal",
  },
  {
    iso_3166_1: "PW",
    english_name: "Palau",
    native_name: "Palau",
  },
  {
    iso_3166_1: "PY",
    english_name: "Paraguay",
    native_name: "Paraguay",
  },
  {
    iso_3166_1: "QA",
    english_name: "Qatar",
    native_name: "Qatar",
  },
  {
    iso_3166_1: "RE",
    english_name: "Reunion",
    native_name: "Réunion",
  },
  {
    iso_3166_1: "RO",
    english_name: "Romania",
    native_name: "Romania",
  },
  {
    iso_3166_1: "RS",
    english_name: "Serbia",
    native_name: "Serbia",
  },
  {
    iso_3166_1: "RU",
    english_name: "Russia",
    native_name: "Russia",
  },
  {
    iso_3166_1: "RW",
    english_name: "Rwanda",
    native_name: "Rwanda",
  },
  {
    iso_3166_1: "SA",
    english_name: "Saudi Arabia",
    native_name: "Saudi Arabia",
  },
  {
    iso_3166_1: "SB",
    english_name: "Solomon Islands",
    native_name: "Solomon Islands",
  },
  {
    iso_3166_1: "SC",
    english_name: "Seychelles",
    native_name: "Seychelles",
  },
  {
    iso_3166_1: "SD",
    english_name: "Sudan",
    native_name: "Sudan",
  },
  {
    iso_3166_1: "SE",
    english_name: "Sweden",
    native_name: "Sweden",
  },
  {
    iso_3166_1: "SG",
    english_name: "Singapore",
    native_name: "Singapore",
  },
  {
    iso_3166_1: "SH",
    english_name: "St. Helena",
    native_name: "St. Helena",
  },
  {
    iso_3166_1: "SI",
    english_name: "Slovenia",
    native_name: "Slovenia",
  },
  {
    iso_3166_1: "SJ",
    english_name: "Svalbard & Jan Mayen Islands",
    native_name: "Svalbard & Jan Mayen",
  },
  {
    iso_3166_1: "SK",
    english_name: "Slovakia",
    native_name: "Slovakia",
  },
  {
    iso_3166_1: "SL",
    english_name: "Sierra Leone",
    native_name: "Sierra Leone",
  },
  {
    iso_3166_1: "SM",
    english_name: "San Marino",
    native_name: "San Marino",
  },
  {
    iso_3166_1: "SN",
    english_name: "Senegal",
    native_name: "Senegal",
  },
  {
    iso_3166_1: "SO",
    english_name: "Somalia",
    native_name: "Somalia",
  },
  {
    iso_3166_1: "SR",
    english_name: "Suriname",
    native_name: "Suriname",
  },
  {
    iso_3166_1: "SS",
    english_name: "South Sudan",
    native_name: "South Sudan",
  },
  {
    iso_3166_1: "ST",
    english_name: "Sao Tome and Principe",
    native_name: "São Tomé & Príncipe",
  },
  {
    iso_3166_1: "SU",
    english_name: "Soviet Union",
    native_name: "Soviet Union",
  },
  {
    iso_3166_1: "SV",
    english_name: "El Salvador",
    native_name: "El Salvador",
  },
  {
    iso_3166_1: "SY",
    english_name: "Syrian Arab Republic",
    native_name: "Syria",
  },
  {
    iso_3166_1: "SZ",
    english_name: "Swaziland",
    native_name: "Eswatini (Swaziland)",
  },
  {
    iso_3166_1: "TC",
    english_name: "Turks and Caicos Islands",
    native_name: "Turks & Caicos Islands",
  },
  {
    iso_3166_1: "TD",
    english_name: "Chad",
    native_name: "Chad",
  },
  {
    iso_3166_1: "TF",
    english_name: "French Southern Territories",
    native_name: "French Southern Territories",
  },
  {
    iso_3166_1: "TG",
    english_name: "Togo",
    native_name: "Togo",
  },
  {
    iso_3166_1: "TH",
    english_name: "Thailand",
    native_name: "Thailand",
  },
  {
    iso_3166_1: "TJ",
    english_name: "Tajikistan",
    native_name: "Tajikistan",
  },
  {
    iso_3166_1: "TK",
    english_name: "Tokelau",
    native_name: "Tokelau",
  },
  {
    iso_3166_1: "TL",
    english_name: "Timor-Leste",
    native_name: "Timor-Leste",
  },
  {
    iso_3166_1: "TM",
    english_name: "Turkmenistan",
    native_name: "Turkmenistan",
  },
  {
    iso_3166_1: "TN",
    english_name: "Tunisia",
    native_name: "Tunisia",
  },
  {
    iso_3166_1: "TO",
    english_name: "Tonga",
    native_name: "Tonga",
  },
  {
    iso_3166_1: "TP",
    english_name: "East Timor",
    native_name: "East Timor",
  },
  {
    iso_3166_1: "TR",
    english_name: "Turkey",
    native_name: "Turkey",
  },
  {
    iso_3166_1: "TT",
    english_name: "Trinidad and Tobago",
    native_name: "Trinidad & Tobago",
  },
  {
    iso_3166_1: "TV",
    english_name: "Tuvalu",
    native_name: "Tuvalu",
  },
  {
    iso_3166_1: "TW",
    english_name: "Taiwan",
    native_name: "Taiwan",
  },
  {
    iso_3166_1: "TZ",
    english_name: "Tanzania",
    native_name: "Tanzania",
  },
  {
    iso_3166_1: "UA",
    english_name: "Ukraine",
    native_name: "Ukraine",
  },
  {
    iso_3166_1: "UG",
    english_name: "Uganda",
    native_name: "Uganda",
  },
  {
    iso_3166_1: "UM",
    english_name: "United States Minor Outlying Islands",
    native_name: "U.S. Outlying Islands",
  },
  {
    iso_3166_1: "US",
    english_name: "United States of America",
    native_name: "United States",
  },
  {
    iso_3166_1: "UY",
    english_name: "Uruguay",
    native_name: "Uruguay",
  },
  {
    iso_3166_1: "UZ",
    english_name: "Uzbekistan",
    native_name: "Uzbekistan",
  },
  {
    iso_3166_1: "VA",
    english_name: "Holy See",
    native_name: "Vatican City",
  },
  {
    iso_3166_1: "VC",
    english_name: "St. Vincent and the Grenadines",
    native_name: "St. Vincent & Grenadines",
  },
  {
    iso_3166_1: "VE",
    english_name: "Venezuela",
    native_name: "Venezuela",
  },
  {
    iso_3166_1: "VG",
    english_name: "British Virgin Islands",
    native_name: "British Virgin Islands",
  },
  {
    iso_3166_1: "VI",
    english_name: "US Virgin Islands",
    native_name: "U.S. Virgin Islands",
  },
  {
    iso_3166_1: "VN",
    english_name: "Vietnam",
    native_name: "Vietnam",
  },
  {
    iso_3166_1: "VU",
    english_name: "Vanuatu",
    native_name: "Vanuatu",
  },
  {
    iso_3166_1: "WF",
    english_name: "Wallis and Futuna Islands",
    native_name: "Wallis & Futuna",
  },
  {
    iso_3166_1: "WS",
    english_name: "Samoa",
    native_name: "Samoa",
  },
  {
    iso_3166_1: "XC",
    english_name: "Czechoslovakia",
    native_name: "Czechoslovakia",
  },
  {
    iso_3166_1: "XG",
    english_name: "East Germany",
    native_name: "East Germany",
  },
  {
    iso_3166_1: "XI",
    english_name: "Northern Ireland",
    native_name: "Northern Ireland",
  },
  {
    iso_3166_1: "XK",
    english_name: "Kosovo",
    native_name: "Kosovo",
  },
  {
    iso_3166_1: "YE",
    english_name: "Yemen",
    native_name: "Yemen",
  },
  {
    iso_3166_1: "YT",
    english_name: "Mayotte",
    native_name: "Mayotte",
  },
  {
    iso_3166_1: "YU",
    english_name: "Yugoslavia",
    native_name: "Yugoslavia",
  },
  {
    iso_3166_1: "ZA",
    english_name: "South Africa",
    native_name: "South Africa",
  },
  {
    iso_3166_1: "ZM",
    english_name: "Zambia",
    native_name: "Zambia",
  },
  {
    iso_3166_1: "ZR",
    english_name: "Zaire",
    native_name: "Zaire",
  },
  {
    iso_3166_1: "ZW",
    english_name: "Zimbabwe",
    native_name: "Zimbabwe",
  },
] as const;

export const TvGenres = [
  {
    id: 10759,
    name: "Action & Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 10762,
    name: "Kids",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10763,
    name: "News",
  },
  {
    id: 10764,
    name: "Reality",
  },
  {
    id: 10765,
    name: "Sci-Fi & Fantasy",
  },
  {
    id: 10766,
    name: "Soap",
  },
  {
    id: 10767,
    name: "Talk",
  },
  {
    id: 10768,
    name: "War & Politics",
  },
  {
    id: 37,
    name: "Western",
  },
] as const;

const ImageSizes = {
  backdrop: ["w300", "w780", "w1280", "original"],
  logo: ["w45", "w92", "w154", "w185", "w300", "w500", "original"],
  poster: ["w92", "w154", "w185", "w342", "w500", "w780", "original"],
  profile: ["w45", "w185", "h632", "original"],
  still: ["w92", "w185", "w300", "original"],
} as const;

export type ImageType = keyof typeof ImageSizes;
export type ImageSize<T extends ImageType> = (typeof ImageSizes)[T][number];
